version: 2.1
jobs:
  build:
    working_directory: ~/errors_db
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - errors_db-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/local.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -Ur requirements/local.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./venv
      - save_cache:
          key: errors_db-py-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/local.txt" }}
          paths:
            - ./venv

  test-python:
    working_directory: ~/errors_db
    docker:
      - image: circleci/python:3.7.3
        environment:
          BUCKETEER_AWS_ACCESS_KEY_ID: circle_test
          BUCKETEER_AWS_SECRET_ACCESS_KEY: circle_test
          BUCKETEER_BUCKET_NAME: circle_test
          DATABASE_URL: postgres://ubuntu@localhost:5432/circle_test
          DB_ENCRYPTION_KEY: ynlw7Du-bwA8EL0gons5cSFjH_7ZY-gZdTaVAFYIEUc=
          DJANGO_DEBUG: False
          DJANGO_HASHID_SALT: test_hash_id
          DJANGO_SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: config.settings.test
          SECURE_SSL_REDIRECT: False
      - image: circleci/redis:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run Database Migrations
          command: |
            . venv/bin/activate
            python ./manage.py migrate --no-input
      - run:
          name: Test Python
          command: |
            . venv/bin/activate
            pytest --junitxml=pycov/pytest-junit.xml
      - store_artifacts:
          path: htmlcov
          destination: py-reports
      - store_test_results:
          path: pycov
      - persist_to_workspace:
          root: .
          paths:
            - .coverage

  check-test-coverage:
    working_directory: ~/errors_db
    docker:
      - image: circleci/python:3.7.3
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report Test Coverage
          command: |
            . venv/bin/activate
            if [[ -z "${COVERALLS_REPO_TOKEN}" ]]; then
              echo ">> env var COVERALLS_REPO_TOKEN is not set; skipping test coverage reporting"
            else
              $VIRTUAL_ENV/bin/coveralls 
              curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
            fi
      - run:
          name: Check Test Coverage
          command: |
            . venv/bin/activate
            coverage3 report --fail-under=100

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-client:
          requires:
            - build
      - test-python:
          requires:
            - build
      - build-docs:
          requires:
            - build
      - check-test-coverage:
          requires:
            - test-client
            - test-python
